name: CI
on:
  push:
  pull_request:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js & pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
          package-manager: 'pnpm'        # ← Bunu ekledik

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
